let resumeData = {
    "imagebaseurl":"https://lowbl-daniel.github.io/",
    "name": "Daniel Low",
    "role": "Technical Designer / Programmer",
    "linkedinId":"",
    "skypeid": "",
    "roleDescription": "",
    "socialLinks":[
        {
          "name":"linkedin",
          "url":"https://www.linkedin.com/in/daniel-low-58530591",
          "className":"fa fa-linkedin"
        },
      ],
    "aboutme":"I am currently a Software Engineer for NUS Cute Center and I graduated with a Bachelor in Science for Computer Science and Game Design at Digipen Singapore jointly under Singapore Institute of Technology (SIT).\n\nI have made my own game engine during my studies in Digipen that utilizes C and C++. In recent jobs, I have created games, simulations and progressive web apps with different languages, as well as worked with queries in MySQL and influxDB.I'm keen expand my technical knowledge in other fields.\n\nIf you wish to know more about my previous works, you may refer to Works for all the projects I have previously worked on.",
    "email": "lowbl.daniel@gmail.com",
    "website":"https://lowbl-daniel.github.io/.",
    "education":[
      {
        "SchoolLogo":"images/Education/Digipen.jpg",
        "UniversityName":"Digipen Institute of Technology",
        "specialization":"Bachelor of Science in Computer Science & Game Design",
        "StartEndDate":"Sep 2011 - 2016",
        "Achievements":""
      },
      {
        "SchoolLogo":"images/Education/NgeeAnnPoly.jpg",
        "UniversityName":"Ngee Ann Polytechnic",
        "specialization":"Diploma in Product Design & Innovation",
        "StartEndDate":"March 2006 - April 2011",
        "Achievements": "⁍Merit Award in FullMark Design Competition 2008\n⁍Best performance in module Product form and Aesthetics 2008"
      }
    ],
    "work":[
      {
        "CompanyLogo":"images/work/CuteCenter.png",
        "CompanyName":"NUS Keio CUTE Center",
        "specialization":"⁍UI Programmer and Gameplay Programmer for Unity 3D\n⁍Worked with VR platforms such as HTC Vive and Oculus\n⁍Worked with Leap Motion, Omni Tracker and custom controllers programmed with Ardunio\n⁍Worked with waterfall / agile methodologies.\n",
        "StartEndDate":"May 2016 - May 2020",
        "Projects":"⁍Basic VIHA (VR anatomy curriculum based software)\n⁍Advanced VIHA ( VR anatomy observation simulation )\n⁍VISE ( VR Surgical Simulation )\n⁍SAFESIM ( First person multiplayer construction site simulation )\n⁍The LostFoxFire(Game that uses multisensory devices, VR / smell / heat).",
        "Achievements":"⁍Virtual Interactive Human Anatomy\nReImagine Education Awards 2019 (Gold) (VIHA)\nhttps://www.reimagine-education.com/regional-2019-award-winners/ \n\n ⁍Safesim\nBEST PAPER in Technology Steam, AUBEA 2018\nhttp://www.bdg.nus.edu.sg/documents/events/Post%20on%20AUBEA%20best%20paper%20award%202018.pdf\n\n⁍The LostFoxFire\nSelected for showcase at TokyoGameShow SOWN 2019\nhttps://www.4gamer.net/games/479/G047904/20190915054/"
      },
      {
        "CompanyLogo":"images/work/pdstudio.png",
        "CompanyName":"PD Design Studios",
        "specialization":"⁍Tools and Editor Programmer for Unity 3D\n⁍AI Programming\n⁍Controls for cross Platform\n⁍Programming using in-house tools as well as 3rd party software\n⁍PS4 / XBox One Development\n⁍Android / IOS Development",
        "StartEndDate":"April 2015 - March 2016",
        "Projects":"⁍One ChangKat (IOS / Android app stores)\n⁍Dusty's Revenge ( PC - deployed to steam)\n⁍Dusty's Revenge Raging Fist (PC - deployed to steam)\n⁍FF7 ReImagined (PC )",
        "Achievements":""
      },
      {
        "CompanyLogo":"images/work/jiangnan.png",
        "CompanyName":"Jiangnan University",
        "specialization":"⁍Graphic Designer\n⁍3D artist",
        "StartEndDate":"September 2018 - November 2008",
        "Projects":"⁍Research on the current trends in the China Market\n⁍Designing of 2D illustrations and 3D modeling for use in  published magazines.\n⁍Training received to use 3D Max VRay Rendering, Rhincerous and Photoshop CS3.",
        "Achievements":""
      }
    ],
    "skillsDescription":"Language / IDE proficiencies",
    "skills":[
      {
        "skillname":"C"
      },
      {
        "skillname":"C++"
      },
      {
        "skillname":"C#"
      },
      {
        "skillname":"CSS"
      },
      {
        "skillname":"HTML5"
      },
	    {
        "skillname":"Javascript"
      },
      {
        "skillname":"MySQL"
      },
      {
        "skillname":"Photoshop"
      },
      {
        "skillname":"Illustrator"
      },
      {
        "skillname":"AfterEffects"
      },
      {
        "skillname":"Autodesk"
      },
      
    ],
    "portfolio":[
      {
        "name":"Virtual Interactive Human Anatomy",
        "description":"A VR project that enhances the user's knowledge of anatomy.",
        "imgurl":"images/portfolio/basicVIHA/VIHA.gif",
        "internalDescription":"A VR project that enhances the user's knowledge of anatomy. The software is split up into six different modules, each focusing on a different section of the body. Information is disseminated to the user with a lecturer's voice, accompanied by the appearance of 3D representations of the anatomy and annotations to better illustrate the concept. Users may also use their controller to point a the models to get the name of that specific body Part. They may also scroll the Vive Trackpad forward or backwards to fast forward or rewind if they miss out on some information. Users may also be quizzed occasionally.",
        "modalPicURL": ["images/portfolio/basicVIHA/VIHA1.png", 
                        "images/portfolio/basicVIHA/VIHA2.png", 
                        "images/portfolio/basicVIHA/VIHA3.png"],
        "videoURL":"",
        "awards":"ReImagine Education Conference 2018 Gold for Regional 2019 : Asia-Pacific category\nhttps://www.reimagine-education.com/regional-2019-award-winners/",
        "roles":"Unity Gameplay programmer\nTools Programmer",
      },
      {
        "name":"Lost FoxFire",
        "description":"The Lost Foxfire' (迷い狐火）is a multi-sensory Virtual Reality project.",
        "imgurl":"images/portfolio/LostFoxFire/lostfoxfire1.png",
        "internalDescription":"The Lost Foxfire' (迷い狐火）is a multi-sensory Virtual Reality (VR) game that uses the sense of heat and smell to find and stop a Foxfire from accidentally burning down your house. The player uses five heat modules to sense heat on the front, back, left, right of the neck, and one for the face. It also uses one smell module to warn the player that the Foxfire is in the room.The additional sensory cues in the form of heat and smell create a more immersive gameplay environment for the players, something rarely seen in current games. This is a gaming experience that uses real sensations not just for immersion, but as a gameplay mechanic!",
        "modalPicURL": ["images/portfolio/LostFoxFire/lostfoxfire1.png",
                        "images/portfolio/LostFoxFire/lostfoxfire2.jpg", 
                        "images/portfolio/LostFoxFire/lostfoxfire3.jpg"],
        "videoURL":"https://www.youtube.com/embed/OcAHtcEkYVg",
        "awards":"The lost foxfire was showcased at Tokyo Gameshow 2019 Sense of wondernight.\nhttps://www.4gamer.net/games/479/G047904/20190915054/\n\nA Zaobao (Singapore chinese newspaper) article about the game\nhttps://www.zaobao.com.sg/znews/singapore/story20191014-997031?themeId=2&utm_expid=.GDliSVqsR_G-lVPCVeIVMg.1&utm_referrer=https%3A%2F%2Fwww.zaobao.com.sg%2F",
        "roles":"Unity Gameplay programmer\nAI Programmer\nVFX Designer",
      },
      {
        "name":"Advanced Virtual Interactive Human Anatomy",
        "description":"VR project that allows the user to observe the human anatomy in VR.",
        "imgurl":"images/portfolio/AdvancedVIHA/AVIHA.gif",
        "internalDescription":"VR project that enhances the user's knowledge of anatomy. It allows the user to observe the human anatomy in VR, accompanied with useful features such as dissection, scaling, rotation, translating, filtering body sections and exploding body parts for context.",
        "modalPicURL": ["images/portfolio/AdvancedVIHA/AVIHA1.png", 
                        "images/portfolio/AdvancedVIHA/AVIHA2.png", 
                        "images/portfolio/AdvancedVIHA/AVIHA3.png"],
        "videoURL":"",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"Safesim",
        "description":"Multiplayer project where you play the role of a construction site supervisor in first person view.",
        "imgurl":"images/portfolio/safesim/safesim.png",
        "internalDescription":"Multiplayer project where you play the role of a construction site supervisor in first person view. You are required to spot hazards and good practices with your camera and these pictures are taken to a album for evaluation.SafeSim was developed as a prototype simulation for construction site workplace safety.",
        "modalPicURL": ["images/portfolio/safesim/safesim1.png", 
                        "images/portfolio/safesim/safesim2.png", 
                        "images/portfolio/safesim/safesim3.png"],
        "videoURL":"https://www.youtube.com/embed/o3-Eir_wa_w",
        "awards":"BEST PAPER in Technology Steam, AUBEA 2018\nhttp://www.bdg.nus.edu.sg/documents/events/Post%20on%20AUBEA%20best%20paper%20award%202018.pdf",
        "roles":"Unity Gameplay programmer\nTools Programmer",
      },
      {
        "name":"Ecosperity",
        "description":"Ecosperity is a Web Progressive Application that displays a household's electrical consumption on a web browser",
        "imgurl":"images/portfolio/Ecosperity/web1.png",
        "internalDescription":"Ecosperity is a Web Progressive Application that displays a household's electrical consumption on a web browser. The smart meter has several channels that is capable of discerning electrical consumption for lighting, water heater, air conditioner and other applications. Data is populated to InfluxDB over time as the smart meter is installed to a HDB owner's household. The owner can tend view the information about electrical consumption on a web browser hosted on an AWS Server.",
        "modalPicURL": ["images/portfolio/Ecosperity/web2.png"], 
        "videoURL":"",
        "awards":"",
        "roles":"FrontEnd Programmer(React, NodeJS, InfluxDB)",
      },
      {
        "name":"Virtual Interactive Car Anatomy",
        "description":"VR project that demostrates the anatomy of a car and extrication process",
        "imgurl":"images/portfolio/VICA/VICA.gif",
        "internalDescription":"This is a rapid prototype with the use of HTC Vive Tracker to replicate the experience of vehicle extrication process used by the Singapore Civil Defence force. There is also another section that allows people to explore the anatomy of a sedan. NUS CUTE Center conducted the Summer Blended reality workshop in May 2019 and we demostrated how we can use VR / AR / MR to solve real world problems. We, the staff of CUTE center, demonstrated our roles and responsibilities when it comes to creating a simulation.",
        "modalPicURL": ["images/portfolio/VICA/VICA1.jpg",
                       "images/portfolio/VICA/VICA2.png",
                       "images/portfolio/VICA/VICA3.png"], 
        "videoURL":"",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"VISE",
        "description":"Multiplayer VR project that allows the user to perform a step-by-step surgery for various operating procedures.",
        "imgurl":"images/portfolio/VISE/vise.png",
        "internalDescription":"Multiplayer VR project that allows the user to perform a step-by-step surgery for various operating procedures.",
        "modalPicURL": ["images/portfolio/VISE/vise1.png",
                       "images/portfolio/VISE/vise2.png",
                       "images/portfolio/VISE/vise3.png"], 
        "videoURL":"",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"Paediatric Anaesthesia",
        "description":"VR game on a mobile phone mounted on a child's face to distract them while Anaesthesia is administered",
        "imgurl":"images/portfolio/PA/pa.png",
        "internalDescription":"Children may experience fear prior to an anaesthesia treatment. The project is an extension of an existing project that also incorporates a deeper immersion in the vr world by creating more realistic art effect through the use of shaders generated through the light weight render pipeline's shader graph and resonance audio. Gameplay is also added for the free time prior to the anaesthesia session.Due to equipment constraints, audio cannot be properly captured using the microphone during the anaesthesia treatment, so a magnet based approach was used for player input. The child would puff his cheek and blow bubbles to shoot at underwater fishes which are colorless and there would be color transition.",
        "modalPicURL": ["images/portfolio/PA/pa.png"], 
        "videoURL":"https://www.youtube.com/embed/rzKQBUfj_qQ",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"BrainAR",
        "description":"This project is used to experiment to see the usefulness of AR to facilitate the session doctors use to strategize an entry point to perform an incision for tumor removal. ",
        "imgurl":"images/portfolio/BrainAR/brainAR.png",
        "internalDescription":"This project is used to experiment to see the usefulness of AR to facilitate the session doctors use to strategize an entry point to perform an incision for tumor removal. ",
        "modalPicURL": ["images/portfolio/BrainAR/brainAR.png"], 
        "videoURL":"https://www.youtube.com/embed/4VMmh3n1pG4",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"Dusty's Revenge Raging Fist",
        "description":"Dusty Raging Fist is a beat-em up game that  is a prequel to the award winning Dusty Revenge.",
        "imgurl":"images/portfolio/DustyRevenge/dr.jpg",
        "internalDescription":"Dusty Raging Fist is a beat-em up game that  is a prequel to the award winning Dusty Revenge.",
        "modalPicURL": ["images/portfolio/DustyRevenge/dr1.jpg",
        "images/portfolio/DustyRevenge/dr2.jpg",
        "images/portfolio/DustyRevenge/dr3.jpg"], 
        "videoURL":"https://www.youtube.com/embed/vDPvQCi3af4",
        "awards":"",
        "roles":"Unity Gameplay programmer (PC, PS4, Xbox1)",
      },
      {
        "name":"Changkat",
        "description":"One Changkat is a point-and-click puzzle adventure game released in conjunction with Changkat Primary School 50th anniversary.",
        "imgurl":"images/portfolio/Changkat/ck.jpg",
        "internalDescription":"One Changkat is a point-and-click puzzle adventure game released in conjunction with Changkat Primary School 50th anniversary.",
        "modalPicURL": ["images/portfolio/Changkat/ck1.jpeg",
                       "images/portfolio/Changkat/ck2.jpeg",
                       "images/portfolio/Changkat/ck3.jpeg"], 
        "videoURL":"",
        "awards":"",
        "roles":"Unity Gameplay programmer (Android / IOS)",
      },
      {
        "name":"FF7Reimagined",
        "description":"Final Fantasy VII: Re-Imagined is a beat-em-up made by fans of the original game",
        "imgurl":"images/portfolio/FF7Reimagined/ff7.jpg",
        "internalDescription":"Final Fantasy VII: Re-Imagined is a project made by fans of the original game. We re-imagined how the game would be like if it’s an action game. Classic 2D Side-scrollers, such as Dragons and Dungeons: Chronicles of Mystara, Streets of Rage, etc, came to our minds. We thought about how we can incorporate some of the FFVII game play elements, such as Materia and Summons into a Hack and Slash genre.",
        "modalPicURL": ["images/portfolio/FF7Reimagined/ff71.jpg",
                       "images/portfolio/FF7Reimagined/ff72.jpg",
                       "images/portfolio/FF7Reimagined/ff73.jpg"], 
        "videoURL":"https://www.youtube.com/embed/-vyDq1WQ24I",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"PoltergeistMansion",
        "description":"Poltergist mansion is a multiplayer turn based android puzzle game where you shift and rotate rooms to connect doors and  guide a wind-up doll to his destination in a haunted house.",
        "imgurl":"images/portfolio/PoltergeistMansion/pm.png",
        "internalDescription":"Poltergist mansion is a multiplayer turn based android puzzle game where you shift and rotate rooms to connect doors and  guide a wind-up doll to his destination in a haunted house.",
        "modalPicURL": ["images/portfolio/PoltergeistMansion/pm1.png",
                       "images/portfolio/PoltergeistMansion/pm2.png",
                       "images/portfolio/PoltergeistMansion/pm3.png"], 
        "videoURL":"https://www.youtube.com/embed/v1IqtzNIlLc",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"CoupDeCube",
        "description":"Coup de Cube is a 4 player cooperative multiplayer Beat'em Up where players can roleplay as a bodyguard who escorts and guards a lord.",
        "imgurl":"images/portfolio/CoupDeCube/coupdecube.png",
        "internalDescription":"Coup de Cube is a 4 player cooperative multiplayer Beat'em Up where players can roleplay as a bodyguard who escorts and guards a lord.",
        "modalPicURL": ["images/portfolio/CoupDeCube/cube1.jpg",
                       "images/portfolio/CoupDeCube/cube2.jpg",
                       "images/portfolio/CoupDeCube/cube3.jpg"], 
        "videoURL":"https://www.youtube.com/embed/lTKk7WQISKA",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"Time Eater",
        "description":"Time eater is a shoot-em-up that uses time as a health point system",
        "imgurl":"images/portfolio/TimeEater/timeeater.png",
        "internalDescription":"Time eater is a shoot-em-up where you play as an android who is sent to kill invading monsters in an apocalyptical future. The android runs on time, which can only be replenished with time bubbles or defeating enemies.",
        "modalPicURL": ["images/portfolio/TimeEater/timeeater1.jpg",
                       "images/portfolio/TimeEater/timeeater2.jpg",
                       "images/portfolio/TimeEater/timeeater3.jpg"], 
        "videoURL":"https://www.youtube.com/embed/kHSeq5sBUJg",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"Viruleon",
        "description":"Viruleon is a top-down scoring game that requires an antivirus to switch between 2 colors to deal with different viruses",
        "imgurl":"images/portfolio/viruleon/viruleon.jpg",
        "internalDescription":"Viruleon is an antivirus that seeks to destroy viruses in a cybernetic system. It can swap between 2 colors, green and orange. By being the same color as the viruses, they can be destroyed, but viruses of the opposing colors will attack Viruleon.",
        "modalPicURL": ["images/portfolio/viruleon/viruleon1.jpg",
                       "images/portfolio/viruleon/viruleon2.jpg",
                       "images/portfolio/viruleon/viruleon3.jpg"], 
        "videoURL":"https://www.youtube.com/embed/VjXKiN2KGSU",
        "awards":"",
        "roles":"Gameplay / Engine (C++) Programmer",
      },
      {
        "name":"Outbreak",
        "description":"Zombie shootout is a single player isometric shooter where you explore an abandoned town in a post apocalyptical world as a to rescue refugees and mow down zombies in your way.",
        "imgurl":"images/portfolio/ZombieShootout/z2.png",
        "internalDescription":"Zombie shootout is a single player isometric shooter where you explore an abandoned town in a post apocalyptical world as a to rescue refugees and mow down zombies in your way.",
        "modalPicURL": ["images/portfolio/ZombieShootout/z1.png",
                       "images/portfolio/ZombieShootout/z2.png"], 
        "videoURL":"https://www.youtube.com/embed/e9jABuw5Bz0",
        "awards":"",
        "roles":"Unity Gameplay programmer",
      },
      {
        "name":"Base Defender",
        "description":"Build automated towers and ultilize the manually controlled turrets around your base to selectively destroy aliens before they mutate.",
        "imgurl":"images/portfolio/BaseDefender/b1.png",
        "internalDescription":"Build automated towers and ultilize the manually controlled turrets around your base to selectively destroy aliens before they mutate.",
        "modalPicURL": ["images/portfolio/BaseDefender/b1.png"], 
        "videoURL":"https://www.youtube.com/embed/3Q2TpuJKNtc",
        "awards":"",
        "roles":"Zero Engine(Python) Gameplay programmer",
      },
      {
        "name":"Fishy Recount",
        "description":"RPG game made with Digipen's early version of zero Engine(Python)",
        "imgurl":"images/portfolio/FishyRecount/fishy1.png",
        "internalDescription":"A hero remembers a certain point in his life when he had to explore a cavern of undead fish in order to look for missing villagers. The special mechanic is the attack feature in which the player has to align the moving sword with the wound on the bar after attacking.",
        "modalPicURL": ["images/portfolio/FishyRecount/fishy1.png",
                       "images/portfolio/FishyRecount/fishy2.png"], 
        "videoURL":"https://www.youtube.com/embed/6OF1VhkWlk4",
        "awards":"",
        "roles":"Zero Engine(Python) Gameplay programmer",
      },
      {
        "name":"Light the Torch",
        "description":"Puzle game made with Construct.",
        "imgurl":"images/portfolio/LightTheTorch/puzzle.png",
        "internalDescription":"Solve each puzzle by lighting up all the torches in 1 try. In order to do that, mirrors must be properly rotated, and time can be manipulated to shift the room around so that the fire can reach its final destination.",
        "modalPicURL": ["images/portfolio/LightTheTorch/puzzle.png"], 
        "videoURL":"https://www.youtube.com/embed/vc8WM4sXOfw",
        "awards":"",
        "roles":"",
      },
      {
        "name":"AI",
        "description":"Collection of AI Algorithms in C++",
        "imgurl":"images/portfolio/AI/astar.gif",
        "internalDescription":"1. AStar/DFS \n 2. Trapezoid\n 3. MinMax \n4. Fuzzy Logic \n5. Genetic Algorithm",
        "modalPicURL": ["images/portfolio/AI/astar.gif",
                        "images/portfolio/AI/navmesh.gif",
                        "images/portfolio/AI/fuzzylogic.gif",
                        "images/portfolio/AI/minimax.gif",
                        "images/portfolio/AI/geneticAlgorithm.gif"], 
        "videoURL":"",
        "awards":"",
        "roles":"Created with c++ custom Engine",
      },
      {
        "name":"Editors",
        "description":"Collections of editor features implemented in Unity",
        "imgurl":"images/portfolio/Editors/e1.gif",
        "internalDescription":"Includes editors tied to scriptable Objects and graphic view to minimize scene change.",
        "modalPicURL": ["images/portfolio/Editors/e2.png",
                        "images/portfolio/Editors/e3.png",
                        "images/portfolio/Editors/e4.png",
                        "images/portfolio/Editors/e5.gif",
                        "images/portfolio/Editors/e6.png",
                        "images/portfolio/Editors/e7.png",
                        "images/portfolio/Editors/e8.png",
                        "images/portfolio/Editors/e9.gif",
                        "images/portfolio/Editors/e10.gif"], 
        "videoURL":"",
        "awards":"",
        "roles":"Unity Programmer",
      },
      {
        "name":"Shaders",
        "description":"Collections of shaders implemented in Unity",
        "imgurl":"images/portfolio/Shaders/1.gif",
        "internalDescription":"Collection of shaders implemented for standard pipeline in Unity. Includes stencil masking, Raymarching, clipping shaders.",
        "modalPicURL": ["images/portfolio/Shaders/2.gif",
                        "images/portfolio/Shaders/3.gif",
                        "images/portfolio/Shaders/4.png",
                        "images/portfolio/Shaders/5.png",
                        "images/portfolio/Shaders/6.png",
                        "images/portfolio/Shaders/7.gif",
                        "images/portfolio/Shaders/8.gif",
                        "images/portfolio/Shaders/9.gif",
                        "images/portfolio/Shaders/10.gif",
                        "images/portfolio/Shaders/11.gif"], 
        "videoURL":"",
        "awards":"",
        "roles":"Unity Programmer",
      },
      {
        "name":"Unreal Level Design",
        "description":"Level Design in unreal Engine",
        "imgurl":"images/portfolio/UnrealLevelDesign/11.png",
        "internalDescription":"Features level design for a multiplayer FPS game and driving game made with Unreal Engine 3 landscaping tools",
        "modalPicURL": ["images/portfolio/UnrealLevelDesign/1.png",
                        "images/portfolio/UnrealLevelDesign/2.png",
                        "images/portfolio/UnrealLevelDesign/3.png",
                        "images/portfolio/UnrealLevelDesign/4.png",
                        "images/portfolio/UnrealLevelDesign/5.png",
                        "images/portfolio/UnrealLevelDesign/6.png",
                        "images/portfolio/UnrealLevelDesign/7.png",
                        "images/portfolio/UnrealLevelDesign/8.png",
                        "images/portfolio/UnrealLevelDesign/9.png",
                        "images/portfolio/UnrealLevelDesign/10.png",
                        "images/portfolio/UnrealLevelDesign/11.png",
                        "images/portfolio/UnrealLevelDesign/12.png",
                        "images/portfolio/UnrealLevelDesign/13.png",
                        "images/portfolio/UnrealLevelDesign/14.png",
                        "images/portfolio/UnrealLevelDesign/15.png",
                        "images/portfolio/UnrealLevelDesign/16.png",
                        "images/portfolio/UnrealLevelDesign/17.png",
                        "images/portfolio/UnrealLevelDesign/18.png",
                        "images/portfolio/UnrealLevelDesign/19.png",
                        "images/portfolio/UnrealLevelDesign/20.png",
                        "images/portfolio/UnrealLevelDesign/21.png",
                        "images/portfolio/UnrealLevelDesign/22.png"], 
        "videoURL":"",
        "awards":"",
        "roles":"Game Design student",
      },
      {
        "name":"Artwork",
        "description":"Collection of programmer Artwork",
        "imgurl":"images/portfolio/Artwork/5.png",
        "internalDescription":"Artwork done by a student programmer",
        "modalPicURL": ["images/portfolio/Artwork/1.jpg",
                        "images/portfolio/Artwork/2.jpg",
                        "images/portfolio/Artwork/3.jpg",
                        "images/portfolio/Artwork/4.jpg",
                        "images/portfolio/Artwork/5.png",
                        "images/portfolio/Artwork/6.jpg",
                        "images/portfolio/Artwork/7.png",
                        "images/portfolio/Artwork/8.png",
                        "images/portfolio/Artwork/9.png",
                        "images/portfolio/Artwork/10.png",
                        "images/portfolio/Artwork/11.png",
                        "images/portfolio/Artwork/12.png",
                        "images/portfolio/Artwork/13.gif",
                        "images/portfolio/Artwork/14.jpg"], 
        "videoURL":"",
        "awards":"",
        "roles":"Student Programmer Artist",
      },
      {
        "name":"Product Design",
        "description":"Collection of 3d Models and 2D illustrations done during my student days",
        "imgurl":"images/portfolio/ProductDesign/main.jpg",
        "internalDescription":"Collection of 3d Models and 2D illustrations done during my student days. Features Engineering drawings (Exploded and dimensions) using ProE CAD software and solidworks, as well as 2D illustrations made with Photoshop, illustrator and CorelDraw",
        "modalPicURL": ["images/portfolio/ProductDesign/1.jpg",
                        "images/portfolio/ProductDesign/2.jpg",
                        "images/portfolio/ProductDesign/3.jpg",
                        "images/portfolio/ProductDesign/4.jpg",
                        "images/portfolio/ProductDesign/5.jpg",
                        "images/portfolio/ProductDesign/6.jpg",
                        "images/portfolio/ProductDesign/7.jpg",
                        "images/portfolio/ProductDesign/8.jpg"], 
        "videoURL":"",
        "awards":"",
        "roles":"Product Designer / Graphic Designer",
      },
    ],
  }
  
  export default resumeData